package com.example.demo;

import java.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;



@RestController
public class TaskController{
	
	@Autowired
	private TaskRepository taskRepository; 
	
/**
 * method of GetMapping to see all the tasks in the BBDD
 * @return List<Task> 
 */
	@GetMapping("/tasks")
	public List<Task> getTask(){
		
		return (List<Task>) this.taskRepository.findAll();
		
		
	}
	
	/**
	 * method of GetMapping to see a task
	 * @param id
	 * @return de task with this param
	 */
	@GetMapping("/taskId")
	public Optional<Task> getTaskId(@RequestParam (value="id") Long id){
		
		return this.taskRepository.findById(id);
		
	}
	
	/**
	 * Method for see the complet tasks
	 * equalsIgnoreCase("Finalizada") accept status Finalizada and finalizada and FINALIZADA
	 * @return List<Task> tasksEnd
	 */
	@GetMapping("/tasksEnd")
	public List<Task> getTaskEnd(){
			
		List<Task> tasks = (List<Task>)this.taskRepository.findAll();
		List<Task> tasksEnd = new ArrayList<Task>();
		for (int i =0 ; i < tasks.size() ; i++ ) {
			
			if(tasks.get(i).getState().equalsIgnoreCase("Finalizada")) {
				tasksEnd.add(tasks.get(i));
			}
		}	
			
	    return tasksEnd;
	}
	
	/**
	 * Method to create new task with id autogenerated and incremental
	 * @param task
	 * @return the new task 
	 */
	@PostMapping("/tasks")
	public Task addTask(@RequestBody Task task) {
		
		return this.taskRepository.save(task);
	}
	/**
	 * Method to update the state of existing Task
	 * @param ID to selec the task to update
	 * @param task body of the new values
	 * @return the task with only update the state
	 */
	@PutMapping("/tasks")
	public Task updateTask(@RequestParam (value="ID")Long ID, @RequestBody Task task){
		Task modTask = taskRepository.findById(ID).get();
		modTask.setState(task.getState());
		return this.taskRepository.save(modTask);
	}
	

	
	/**
	 * Method to delete a task
	 * in the body of DELETE REST it needs the id the other no necesary
	 * @param task
	 */
	@DeleteMapping("/tasks")
	public void deleteTask(@RequestBody Task task) {
		this.taskRepository.delete(task);
	}
	



}